version: '3.9'
services:
  decanatsurveillance:
    container_name: decanatsurveillance
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - dbdecanat

  dbdecanat:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
    volumes:
      - /./dbdata/var/lib/postgresql
   
    


    

  